### ISSUE TITLE
Model service not running on MAC applehv and linux

### ISSUE THREAD

**Issue by lstocchi** [projectatomic/ai-studio#130]
Philippe discovered that the model service cannot be actually run after creation with https://github.com/projectatomic/studio-extension/pull/100 on MAC applehv.

Error
```
Traceback (most recent call last):
  File "/locallm/chat_service.py", line 9, in <module>
    llm = Llama(os.getenv('MODEL_PATH',
  File "/opt/app-root/lib64/python3.9/site-packages/llama_cpp/llama.py", line 276, in __init__
    raise ValueError(f"Model path does not exist: {model_path}")
ValueError: Model path does not exist: /llama-2-7b-chat.Q5_K_S.gguf
```

Also broken on Linux

**Comment by lstocchi** [comment]
Start investigating, if someone has any info pls share here

**Comment by jeffmaury** [comment]
I would guess that's because volume mounts is not implemented on applehv

**Comment by lstocchi** [comment]
But if i execute it from the cli it works

**Comment by lstocchi** [comment]
Ok so i'm able to replicate the error we face using the CLI if i forget to add the Z flag to the command
Working command
```
podman container create -v localSource:/model.gguf:Z --env MODEL_PATH=/model.gguf modelimage
```

Non-working command -> same result as running with Desktop
```
podman container create -v localSource:/model.gguf --env MODEL_PATH=/model.gguf modelimage
```

**Comment by lstocchi** [comment]
closing as https://github.com/projectatomic/ai-studio/pull/231 has been merged and the model mounting works on applehv/linux
