### ISSUE TITLE
AI studio tries to download x86 cuda model on mac m3 (aarch64)

### ISSUE THREAD

**Issue by feloy** [projectatomic/ai-studio#141]
![Capture d’écran 2024-01-25 à 15 26 34](https://github.com/projectatomic/studio-extension/assets/9973512/132b0357-e233-4627-85ab-4dcc3218477a)

**Comment by jeffmaury** [comment]
Should be handled by bab96a0a3745d94fe5106df9a70e996f94b2b5d5

**Comment by slemeur** [comment]
Closing as the PR has been merged
