### ISSUE TITLE
Playground should look similar to a chat

### ISSUE THREAD

**Issue by lstocchi** [projectatomic/ai-studio#145]
I think that the playground should have a look similar to a chat. 
The input field on the bottom and all the messages on the scrollable top.
Being able to only send one request and do not see the old requests/responses is not that nice
E.g
![image](https://github.com/projectatomic/studio-extension/assets/49404737/e0da6c9a-fd95-4135-8a50-57c93fe6d32b)

**Comment by slemeur** [comment]
fix in 0.3
