### ISSUE TITLE
Add option to tag/name a resulting image when pulling a sample

### ISSUE THREAD

**Issue by lstocchi** [projectatomic/ai-studio#161]
user should have an option to tag/name the resulting image when pulling a sample. 
The images when built by ai studio are listed as docker.io/library/chatbot-example.

Should we add a field in the ai-yaml for image-name so it is used as default?

**Comment by sallyom** [comment]
This would be a big improvement!

**Comment by slemeur** [comment]
should be based on the information in the ai-studio.yaml

**Comment by slemeur** [comment]
If default names are incorrect - user should be pointed to the image screen to rename them.
