### ISSUE TITLE
Images generated for a model service should get a badge similar to bootc

### ISSUE THREAD

**Issue by lstocchi** [projectatomic/ai-studio#162]
model-service: true  images should get a badge similar to bootc

**Comment by lstocchi** [comment]
@mairin which icon can we use?

**Comment by deboer-tim** [comment]
For badges you just pick a color... are you changing the icon as well?

**Comment by lstocchi** [comment]
Ah you're right, i was thinking about the icon on the left 🤦

**Comment by jeffmaury** [comment]
Blocked by https://github.com/containers/podman-desktop/issues/5851
