### ISSUE TITLE
Improved playground support

### ISSUE THREAD

**Issue by jeffmaury** [projectatomic/ai-studio#175]
Here are the tasks:

- [x] #147 
- [x] #23
- [x] #186
- [x] #110
- [x] #57
- [x] #188
- [x] #191
- [x] #46

**Comment by axel7083** [comment]
We can add 

- [ ] https://github.com/projectatomic/ai-studio/issues/186
- [ ] https://github.com/projectatomic/ai-studio/issues/188

**Comment by slemeur** [comment]
Closing as all issues completed
