### ISSUE TITLE
playground not generating responses

### ISSUE THREAD

**Issue by lstocchi** [projectatomic/ai-studio#220]
### Bug description

When interacting with the playground, a response is not received, and error is shown (screenshot below)

### Operating system

macOS Sedona

### Version

next (development version)

### Steps to reproduce

Install extension, start Models > Llama2-7b.. > Playground

### Additional context

<img width="1630" alt="Screenshot 2024-02-02 at 9 45 58 AM" src="https://github.com/containers/podman-desktop-extension-bootc/assets/11166065/4ffe95d3-6a15-44f8-8d53-48b721f1aa87">

**Comment by jeffmaury** [comment]
Is it the same as #147 ?

**Comment by lstocchi** [comment]
I copied it from the bootc repo as Sally used the wrong repo https://github.com/projectatomic/ai-studio/issues/220 
But i think it is the same.

**Comment by jeffmaury** [comment]
Duplicates #147
