### ISSUE TITLE
mock for environment page

### ISSUE THREAD

**Issue by feloy** [projectatomic/ai-studio#235]
As discussed during Feb-06 UX call, the pages would display a list of environments, with high-level information (status, address/port to access app, etc, operations: stop/start/...)

The pod/containers details could be accessed by clicking a link sending the user to the pod details page on podman desktop (similar to accessing the Playground container)

**Comment by feloy** [comment]
> ![image](https://private-user-images.githubusercontent.com/799683/304115422-aef47086-d9a5-4aaa-ad5c-32c69d853711.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDgwNjAsIm5iZiI6MTcwNzc0Nzc2MCwicGF0aCI6Ii83OTk2ODMvMzA0MTE1NDIyLWFlZjQ3MDg2LWQ5YTUtNGFhYS1hZDVjLTMyYzY5ZDg1MzcxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxNDIyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWFhOWY4YWI2M2I4ZDE3ZmUzODBiNGRjODdjOTQ5MzAwZGM4YTc5ZTNlNDU5MWZhZTQ2YWVmYzNhMjUzNThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I1xhW_RVE0u762gtqWZ3QzOQlLvQnh21EoBhQMWPS_c)
> 
> Here's one thought - but I wonder if we should call this applications instead of environments? What do you think?

Yes, this design seems very nice to me. And I cannot see any blocker to implement it (note: #253 will help get the information about the availability of model and app)

**Comment by jeffmaury** [comment]
> ![image](https://private-user-images.githubusercontent.com/799683/304115422-aef47086-d9a5-4aaa-ad5c-32c69d853711.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDkyMDgsIm5iZiI6MTcwNzc0ODkwOCwicGF0aCI6Ii83OTk2ODMvMzA0MTE1NDIyLWFlZjQ3MDg2LWQ5YTUtNGFhYS1hZDVjLTMyYzY5ZDg1MzcxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxNDQxNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Yzc5ZDYyZDA4NDkxMzVmYzYzY2JkOTg5NmM0ZWNjMDE1Y2UyYzhiMTAxNzQ5OWYyYzYzNmI4NWNkMmRmOTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.b1hjUYjrrm0RiWR8AA4Zy1aeqHSXe7Nx24ZSDrm1gbA)
> 
> Here's one thought - but I wonder if we should call this applications instead of environments? What do you think?

AI applications
