### ISSUE TITLE
recipe details page having application details partially hidden when opening IA-Studio

### ISSUE THREAD

**Issue by axel7083** [projectatomic/ai-studio#238]
When opening Podman-Desktop with the latest version of AI-Studio I am getting the following windows

![image](https://github.com/projectatomic/ai-studio/assets/42176370/111f97c2-5836-4713-8e60-b16c11bf43bd)

> I did not resized my windows

cc @lstocchi

**Comment by axel7083** [comment]
I started investigating, it comes from the <code> html element inside the markdown i will assign myself

**Comment by axel7083** [comment]
Okey the problem is **annoying** the `<pre>` html element is using the `white-space: pre` which _magically_ set some kind of arbitrary width value, and the only way to prevent it is to set manually `max-width`  with a defined value but I can't make it works.

I tried making the with calculable of the markdown `max-width: calc(100% - 375px);` but without much success.

cc @feloy @lstocchi if you are motivated

**Comment by lstocchi** [comment]
Just saw this on the MAC now, quite annoying and almost unusable as it doesn't scroll horizontally. I'll try to give it a look later if nobody do it earlier

**Comment by lstocchi** [comment]
and thanks for the explanation @axel7083 👍

**Comment by axel7083** [comment]
The only solution I thought are to make the application details position absolute, the markdown too. 

Then set the `right` css property of application details to `0px`.
For the markdown component set  `max-width: calc(100% - 375px)` however, it has a lot of issue, especially when changing tabs

Good luck @lstocchi

**Comment by feloy** [comment]
Not sure if it is the same thing that Axel describes, but I would see the application details as a 'floating' window, which would overlap the markdown when it is opened, so the markdown would always have the complete width for being displayed.

**Comment by axel7083** [comment]
> Not sure if it is the same thing that Axel describes, but I would see the application details as a 'floating' window, which would overlap the markdown when it is opened, so the markdown would always have the complete width for being displayed.

No I am not suggesting having a flotting island, as it would clearly hide the markdown and make it complicated to read. Imagine having a very very long first paragraph in the markdown, you could never read it, as bigger your windows will get, the paragraph will always fill all the space, and the `floating` island would always be hidden a part of it

**Comment by axel7083** [comment]
I have a working solution waiting for https://github.com/projectatomic/ai-studio/pull/252 to be merged
