### ISSUE TITLE
persistence : we need to know when starting which recipe are already pulled

### ISSUE THREAD

**Issue by axel7083** [projectatomic/ai-studio#250]
When enabling/disabling the AI-Studio or the Podman-Desktop application, we probably need some kind of mechanism to persist the information of what recipes are already pulled.

We can probably have some kind of json saved somewhere, what do you think @jeffmaury

**Comment by jeffmaury** [comment]
Can't we rely on the git repo presence and pod state ?

**Comment by axel7083** [comment]
We can I guess

**Comment by axel7083** [comment]
The how about this https://github.com/projectatomic/ai-studio/issues/234 what if the user want to provide either a git url, or a url folder

**Comment by jeffmaury** [comment]
> @jeffmaury then how about this #234 what if the user want to provide either a git url, or a url folder

I don't see the issue there as what we're trying to handle is the case where the repo is already download but on a different commit so I would say the git metadata would allow us to handle it properly
