### ISSUE TITLE
Handled remote models in playground

### ISSUE THREAD

**Issue by axel7083** [projectatomic/ai-studio#257]
The user is able to navigate to the playground of a model which **is not on disk** leading to an error.

What are the expected behaviour we want to achieve ? We need to improve the playground page in the case the models is not on disk. 

- Prevent the user to access the playground page if not available on disk (hide the playground tab)
- Add a download button in the playground page

cc @jeffmaury

**Comment by sallyom** [comment]
rather than hide the tab, i'd prefer if the extension can check if model is on disk, and if not download it - probably ask user if they want to download it first -  it takes a few mins to download so also give a message that it's downloading.

**Comment by jeffmaury** [comment]
Add a download button in the playground UI looks better

**Comment by axel7083** [comment]
No longer required
