### ISSUE TITLE
add & update sample applications from locallm repository

### ISSUE THREAD

**Issue by sallyom** [projectatomic/ai-studio#262]
* [This chatbot application](https://github.com/redhat-et/locallm/blob/main/chatbot-langchain/ai-studio.yaml) should replace the current chatbot sample
  * eventually the [older chatbot application](https://github.com/redhat-et/locallm/blob/main/chatbot/ai-studio.yaml) will be removed from locallm 
* [sample RAG application](https://github.com/redhat-et/locallm/blob/main/rag-langchain/ai-studio.yaml)

**Comment by slemeur** [comment]
Part of this issue has been addressed previously - following on the RAG sample here: https://github.com/projectatomic/ai-studio/issues/474
