### ISSUE TITLE
feat: Add ability to open sample application in the IDE

### ISSUE THREAD

**Issue by slemeur** [projectatomic/ai-studio#27]
Once the sample application has been cloned locally:

<img width="316" alt="Screenshot 2024-01-15 at 09 57 20" src="https://github.com/projectatomic/studio-extension/assets/1636769/93f335b4-f8ee-4616-affe-b529c37d567c">

Add a button enabling to open the source code in an IDE. Could start with VSCode to start with.

**Comment by axel7083** [comment]
Depends on https://github.com/containers/podman-desktop/issues/5672
