### ISSUE TITLE
download models methods should not be bounded to a recipe

### ISSUE THREAD

**Issue by axel7083** [projectatomic/ai-studio#336]
The download method in the model manager requires a RecipeStatusUtils object in its parameters.

The RecipeStatusUtils is bounded to a recipe, and if we want to be able to download the models from the models page, we need to make is not bounded to this object;

**Comment by feloy** [comment]
The parameter has been set as optional, to not be bound to it. It has been added to be able to chain several operations and add tasks to the same Task list. A kind of _context_.

Probably use an Options parameter instead?

**Comment by axel7083** [comment]
https://github.com/projectatomic/ai-studio/blob/4b65712a25fd1115081342d39e10092179b5ad81/packages/backend/src/managers/modelsManager.ts#L180

it is not optional

**Comment by feloy** [comment]
Ah sorry, I was looking at the definition of `pullApplication`
