### ISSUE TITLE
improve tasks management system 

### ISSUE THREAD

**Issue by axel7083** [projectatomic/ai-studio#339]
During the hackaton it was easier to include the tasks inside the state of the recipe. However this architecture is hard to maintain. The tasks should be independents items, they already support `labels` a dictionary of `string->string`. 

When a recipe operation is creating tasks it should add its id as label, e.g. `"recipe-id": "dummy-id"`. Then on the frontend, we should have a dedicated store for the Tasks.

- [x] https://github.com/projectatomic/ai-studio/issues/336 
- [x] #382
- [x] #343
- [x] Stop using custom id for tasks (we use `recipeId` and `modelId` to avoid conflicts today, we should move out of this behaviour)
- [x] #384
> When we download a model from the Models page, ad start the application from the recipe page, it can creates some issue

**Comment by slemeur** [comment]
Closing all tasks completed
