### ISSUE TITLE
Application and model ports are not known

### ISSUE THREAD

**Issue by feloy** [projectatomic/ai-studio#356]
For #235, we need to know which are the ports for the application and the model.

Looking at the pod's or containers's ports is not enough, as all ports are declared for each container and for the pod (as containers are in the same pod), and there is no way to distinguish which one is for the app and which one for the model.

As I understand, the application Manager makes the assertion that the port of the model if the first port declared for the model's container, but it could be the second, depending on which port is smaller.

**Comment by jeffmaury** [comment]
Model port should not be necessary with the changes to the configuration file

**Comment by feloy** [comment]
In the design #235, the model port is displayed. I'm not sure why, but I can imagine the developer may want to make some manual requests on the model for testing, and the information is useful.

**Comment by lstocchi** [comment]
Now there is the `ports` field within ai-studio.yaml that specify the ports used by each item. 
As soon as i finish to update the catalog we should be good with all recipes.
