### ISSUE TITLE
application always in `Starting` state

### ISSUE THREAD

**Issue by axel7083** [projectatomic/ai-studio#366]
![image](https://github.com/projectatomic/ai-studio/assets/42176370/f285942e-32c8-48aa-a4e0-4161986f8877)

![image](https://github.com/projectatomic/ai-studio/assets/42176370/7c0ffffd-2aa1-4396-bb82-98e77f03fda5)

## logs _llamacpp-server-podified-1708336388465_
![image](https://github.com/projectatomic/ai-studio/assets/42176370/f5d25400-ad81-4386-a268-a9137ff1d5d3)

**Comment by axel7083** [comment]
cc @feloy

**Comment by feloy** [comment]
Related to https://github.com/projectatomic/ai-studio/pull/354#issuecomment-1952022277

**Comment by lstocchi** [comment]
Yes, looking at it 👍

**Comment by lstocchi** [comment]
Closing as new versions of chatbot, summarizer and code-generation apps have been added to the catalog. You should not see this anymore with the new apps
