### ISSUE TITLE
Provide Model Serving snippet for Java base

### ISSUE THREAD

**Issue by jeffmaury** [projectatomic/ai-studio#404]

**Comment by jeffmaury** [comment]
@slemeur we have one base on OkHttp, do you think it is ok or should get one based on raw JDK runtime

**Comment by lstocchi** [comment]
The unirest snippet is correct for me

**Comment by lstocchi** [comment]
Closing as https://github.com/projectatomic/ai-studio/pull/626 has been merged and java unirest code is ok
