### ISSUE TITLE
Provide Model Serving snippet for Python base (OpenAI library or HTTP library)

### ISSUE THREAD

**Issue by jeffmaury** [projectatomic/ai-studio#405]

**Comment by MichaelClifford** [comment]
@jeffmaury are these the types of snippets you are looking for for python? 

https://github.com/redhat-et/locallm/blob/main/playground/tooling_options.ipynb

**Comment by jeffmaury** [comment]
> @jeffmaury are these the types of snippets you are looking for for python?
> 
> https://github.com/redhat-et/locallm/blob/main/playground/tooling_options.ipynb

Yes exactly. Thanks for the input

**Comment by slemeur** [comment]
fixed by #607
