### ISSUE TITLE
Upload model on podman machine so model service starts quickly - QEMU

### ISSUE THREAD

**Issue by lstocchi** [projectatomic/ai-studio#421]
Same as #420 but on QEMU. It needs https://github.com/containers/podman-desktop/pull/5848 to be merged

**Comment by slemeur** [comment]
As we'll be with Podman 5.0 and AppleHV, is this still relevant?

**Comment by lstocchi** [comment]
@slemeur no, on applehv this is not necessary. So, with podman 5, qemu will not be used anymore?

**Comment by benoitf** [comment]
Qemu backend is dropped for macOS on Podman v5

**Comment by slemeur** [comment]
closing, as will be fixed with podman 5
