### ISSUE TITLE
Provide a landing page for the studio

### ISSUE THREAD

**Issue by slemeur** [projectatomic/ai-studio#44]
As a user, when I first open the Studio, I'm landing on a dashboard. at the moment this dashboard is empty, but we should be providing explanations about what the Studio is for and how to use it.

Maybe, we could make it load an markdown file, so the content would be easy to load.

**Comment by lstocchi** [comment]
@slemeur @mairin do you have any text for this page? or mockup?

**Comment by vrothberg** [comment]
I think @jeffmaury is writing a README at the moment.  The text can be recycled to also be displayed on the landing page.

At the present, I expect new users to be quite lost when starting the extension:
![image](https://github.com/projectatomic/ai-studio/assets/11679875/590b4f5d-c3e2-4811-9bec-61ce6e806bf5)
