### ISSUE TITLE
Recipe Catalog entries are dissapearing

### ISSUE THREAD

**Issue by mrguitar** [projectatomic/ai-studio#446]
I updated the ai plugin on March 4th, and I could use the code gen application. Cloning it worked perfectly, earlier versions would just spin and not seem to do anything. This time it worked great; however, the next day the plugin no longer shows the code gen application. I can see the repo cloned under ~/podman-desktop/codegeneration along w/ the model, but neither can be viewed from the plugin any more. 

Sorry I don't know how to report the exact version I'm running or more details.

**Comment by axel7083** [comment]
Hi @mrguitar thanks for reporting this issue! 

- Could you tell me which version of `Podman-Desktop` you are using ?
- Could you also explain how you installed the AI-Studio ?

If you have some time to replicates, and extract the logs, we would really appreciate, to do so, here are the steps to follow:

**(1)** Go to `settings` -> `extensions` -> `AI Studio` and check if there is an error in this page
<img width="783" alt="image" src="https://github.com/projectatomic/ai-studio/assets/42176370/442a569c-147a-41df-9bd8-0b5abae9faf7">

If there is, please copy it and paste it in this issue.

**(2)** **Disable** then **Enable** the extension

> This step is to ensure the last logs will contain the potential error.

**(3)** Go to the `troubleshoot` page
<img width="193" alt="image" src="https://github.com/projectatomic/ai-studio/assets/42176370/eea4ba15-fc4c-42f0-87e4-30b2fbaf553b">
**(4)** Select the `Logs` tab
**(5)** Copy/paste the content in this issue

**Comment by mrguitar** [comment]
I'm on version 1.7.1.
I installed the extension by pasting: ghcr.io/projectatomic/ai-studio:latest into Install a new extension from OCI Image

There isn't any visible text under the extension like in your screenshot. 

Here are the logs. I didn't see anything obvious, but hopefully you'll see the issue. After disabling/enabling the plugin, the codegen app still isn't showing in the UI. 
[podman.log](https://github.com/projectatomic/ai-studio/files/14502340/podman.log)

**Comment by mrguitar** [comment]
FYI, switching to the :nightly tag on the plug in brought back the app that disappeared. I believe this is resolved so I'm closing this.
