### ISSUE TITLE
Polish list of Models UI

### ISSUE THREAD

**Issue by slemeur** [projectatomic/ai-studio#479]
- icons
- font styles
- table and pre-requisites

**Comment by feloy** [comment]
@slemeur could you please point to the mockup you are refering to?

**Comment by vrothberg** [comment]
@feloy do you have everything you need or are there open questions?

**Comment by feloy** [comment]
> @feloy do you have everything you need or are there open questions?

I need more information about the **icon** and **table and pre-requisites**

- icon: for the moment, there is no icon field for the models definition in the catalog file `ai.json`. Do we want to add it?

- table and pre-requisites: which pre-requisites?

**Comment by jeffmaury** [comment]
> > @feloy do you have everything you need or are there open questions?
> 
> I need more information about the **icon** and **table and pre-requisites**
> 
>     * icon: for the moment, there is no icon field for the models definition in the catalog file `ai.json`. Do we want to add it?
> 
>     * table and pre-requisites: which pre-requisites?

Icon could be based on registry

**Comment by vrothberg** [comment]
@slemeur PTAL

**Comment by vrothberg** [comment]
@jeffmaury WDYT?

**Comment by jeffmaury** [comment]
> @jeffmaury WDYT?

Discussed with @slemeur yesterday

**Comment by feloy** [comment]
As discussed during UX call (22/03):
- we will display a generic Model icon on each line (we cannot use the Hugging Face icon). The icon could be colorized to differentiate downloaded models from others
- the cpu/gpu prerequisite is already displayed (HW Compat column)
- we won't display the size of the file
- we will display the memory required (this information needs to be added first to the model's information in the catalog)

**Comment by slemeur** [comment]
Also please use consistent font sizes with the list of containers

**Comment by slemeur** [comment]
Please keep the size of the model.

**Comment by feloy** [comment]
> * we won't display the size of the file when the model is not downloaded

> we won't display the size of the file **when the model is not downloaded**

This was probably not clear. It has beensaid to not display the size of the file **before the model is downloaded**, but we will keep the file size once it is on disk.

**Comment by slemeur** [comment]
OK perfect! thanks for clarifying

**Comment by feloy** [comment]
> Also please use consistent font sizes with the list of containers

I have created this issue https://github.com/projectatomic/ai-studio/issues/667. We need to be careful as this can have impact on many other places
