### ISSUE TITLE
Provide ability to manage the local models

### ISSUE THREAD

**Issue by slemeur** [projectatomic/ai-studio#50]
Once a model is loaded locally, as a user I'd like the following options:
- Being able to open the folder where the model is loaded
- Check if I have the latest version of the model
- Delete the model

**Comment by feloy** [comment]
Needs #116

**Comment by feloy** [comment]
> * Check if I have the latest version of the model

Are models versioned for now? How? @slemeur @jeffmaury

**Comment by nichjones1** [comment]
@feloy this was from the prior sprint, is it still postponed?

**Comment by feloy** [comment]
This question is still open: 

> Are models versioned for now? How? @slemeur @jeffmaury

**Comment by slemeur** [comment]
As most of the issues have been handled, closing in favor of https://github.com/projectatomic/ai-studio/issues/466
