### ISSUE TITLE
prettier&linter issue

### ISSUE THREAD

**Issue by axel7083** [projectatomic/ai-studio#513]
When a string has quoted string inside it for example
`const a = "hello 'world'"` 

When running the linter we get

`const a = 'hello \'world\''` 

but prettier detect an error and fix it by making

 `const a = "hello 'world'"` 

which is detected as an error for the linter

I tried playing with https://prettier.io/docs/en/options.html#quote-props but without success

Solution (hack)

replace with <code>const a = \`hello 'world'\`</code>

**Comment by benoitf** [comment]
the hack is the recommended solution for this case

**Comment by axel7083** [comment]
Closing as will not be resolved
