### ISSUE TITLE
model displayed after cancelling download

### ISSUE THREAD

**Issue by vrothberg** [projectatomic/ai-studio#517]
When closing Podman Desktop while downloading a mode, the model is being displayed suggesting it can be used.

I _suspect_ that the model is being downloaded to the final destination directly; writing it to a temp directory + rename may be safer.

![image](https://github.com/projectatomic/ai-studio/assets/11679875/76997a01-cf8e-4640-99fb-81f2f5c3a1ee)

**Comment by benoitf** [comment]
hello @vrothberg are you using the current main branch ?

b/c last week there was https://github.com/projectatomic/ai-studio/issues/389 and https://github.com/projectatomic/ai-studio/pull/458

**Comment by vrothberg** [comment]
I was using the `nightly` build?  Are those less nightly than the name suggests?

**Comment by benoitf** [comment]
`nightly` is published at each commit so should be good.
just wanted to double check

About your issue and the wording, closing means that you closed the Podman Desktop window or you exited Podman Desktop ? (if the window is only closed it is staying in the background)

**Comment by vrothberg** [comment]
I ran on Linux which AFAIK closes Podman Desktop entirely.

**Comment by benoitf** [comment]
I'm able to reproduce

so you see in the 'Downloaded' section but not in the 'Available' section (as file is not completed)

but yes probably it's confusing

**Comment by axel7083** [comment]
https://github.com/projectatomic/ai-studio/blob/3aa45002b477cb79bbe200637a2242ccffb922b0/packages/backend/src/utils/downloader.ts#L88-L95

We already are using a `*.tmp` file name for the download and renaming it on download finish, @vrothberg can you `ls` the folder of the model to see the file in it ?
