### ISSUE TITLE
[possible BUG] IP address shown in PD pod log is http://0.0.0.0:port_number

### ISSUE THREAD

**Issue by rostalan** [projectatomic/ai-studio#523]
Testing 1.8.0 of PD with podman 4.9.3, 
going through the steps described [here](https://github.com/odockal/podman-desktop-qe/pull/13).
When looking up the local URL (line 21 of the guide), I found this line in pod log: 
`Running on local URL:  http://0.0.0.0:7860`
When connecting to this address, it returns "Unable to connect" error. When I manually switch it to localhost address, it displays the local app as expected.

My question is whether this is the expected behaviour?

**Comment by jeffmaury** [comment]
Yes that is a log from inside the container you should use localhost to connect to that port
