### ISSUE TITLE
Create Playground page

### ISSUE THREAD

**Issue by jeffmaury** [projectatomic/ai-studio#525]
A playground page should be added in the navigator bar (left)

That page should list existing playground sessions/conversation with a model and its inteference server

It should also be possible to create a new playground session from there

- [x] #539
- [x] #570
- [x] #580 
- [x] #613 
- [x] #543
- [ ] ~~Code snippets (milestone 1.0)~~
- [x] Make submitPlaygroundMessage reply more quickly (call to `new OpenAI` is too long?)
- [x] #595
- [x] #615 
- [x] #617

**Comment by axel7083** [comment]
depends on https://github.com/projectatomic/ai-studio/issues/509

**Comment by feloy** [comment]
Mockup for playground page:

![model_details_stable_diffusion_playground](https://github.com/projectatomic/ai-studio/assets/9973512/43331230-3f18-4c6b-b221-763577010522)

**Comment by feloy** [comment]
done
