### ISSUE TITLE
Add ability to open the sample application once started

### ISSUE THREAD

**Issue by slemeur** [projectatomic/ai-studio#61]

**Comment by axel7083** [comment]
@slemeur can we have more details on how the extension will know _What is the application ?_

I think we need to add this insight inside the `ia-studio.yaml`. We add a tag/labels explicitly stating it the application (frontend) run on this container and expose this/those port.

If we agree, then this story depends on https://github.com/projectatomic/studio-extension/issues/59 which should include those informations (cc @lstocchi )

**Comment by slemeur** [comment]
linking to #74

**Comment by slemeur** [comment]
Agree, that's maybe a metadata that would be nice to be provided with `ai-studio.yaml` - or the open app just list the expose ports and the user clicks to open it.

**Comment by lstocchi** [comment]
Can't we rely on the Containerfile expose directive? 🤔

**Comment by feloy** [comment]
blocked by #356
