### ISSUE TITLE
Prevent modification of the system prompt after having started the playground's discussion

### ISSUE THREAD

**Issue by slemeur** [projectatomic/ai-studio#617]
Following the work on #591 we would like to improve the behavior to be more consistent with how system prompt are used.

- The system prompt should be defined ONLY before starting the conversation.
- Once the conversation started, the system prompt is not editable anymore. 
- The user will see a message saying "Modifying the system prompt will significantly impact your entire playground. Unfortunately, you have limited options to make changes once the conversation has begun. Create a new playground and adjust the system prompt prior to initiating the interaction."

**Comment by axel7083** [comment]
i think we should emphasize that the system prompt is a message on itself, and by this meaning is part of the conversation. Maybe it should be taken out of the settings section, and put it above the chat

**Comment by axel7083** [comment]
Here is a mockup of what I am thinking about would be more friendly for developers to have a better understanding of how it works.

![image](https://github.com/projectatomic/ai-studio/assets/42176370/d0540eeb-1ed7-46c8-93ab-9754713cab64)

- It clearly show to the user that it is something above the conversation and part of it
- it differentiate from the settings which are customizable for each call
- We can then include the system prompt inside the conversations in the same way than chats.

**Comment by slemeur** [comment]
Ok.
For the time being, I prefer we don't give the ability to change the system prompt and handle that as part of #618.

@feloy: what do you think about the impact of moving the system prompt configuration this direction?

**Comment by feloy** [comment]
It's not completely clear how this system prompt box should behave:
- why an edit button?
- What is present before we send the first prompt, and what happens if we send the first prompt with setting the system prompt? (I have my opinion, but just to be sure we agree)

**Comment by slemeur** [comment]
We would add the "edit button" only as part of #618 .

> What is present before we send the first prompt
If a first prompt is sent before configuring the system prompt - the system prompt will not be editable anymore. 

> what happens if we send the first prompt with setting the system prompt?
We put the system prompt first and then the first prompt

**Comment by feloy** [comment]
> @feloy: what do you think about the impact of moving the system prompt configuration this direction?

OK, I'll make the changes this way

**Comment by axel7083** [comment]
I made a few mockup in addition to show the path the user could follow if we agree on this

**new conversation layout**

![image](https://github.com/projectatomic/ai-studio/assets/42176370/0f9275bf-656f-4a4a-936d-3d154839826a)


**clicked on edit button**

![image](https://github.com/projectatomic/ai-studio/assets/42176370/7e15a9b7-0533-4501-a837-97499d45527f)

**Comment by feloy** [comment]
A first draft is visible at https://github.com/projectatomic/ai-studio/pull/625
Still have to finalize the design and write tests / fix bugs

**Comment by feloy** [comment]
As discussed during the UX call (22/03), the system prompt will be asked to the user in the creation form (when asked for an optional name and for a model). The system prompt will be displayed as soon as the playground page is opened, as a System message.

**Comment by slemeur** [comment]
We'll have an "advanced settings" section at the time we start the playground? 
The system prompt is really optional, and is likely going to be something that you configure after having done a couple of iterations, playing with the model. 
We should make the user being able to get the playground env, as fast as possible, get him/her test, play, hack and understand what's going on. 

I think this is not a great idea, especially for a first time user, to show a form with a lot of different options that they might not be familiar with (yet).

**Comment by feloy** [comment]
> Will we have an "advanced settings" section at the time we start the playground? The system 

It has not been discussed, but we could have, yes. Please look at the demo at #643. If you feel we should place the option in an 'Advanced settings' block, hidden by default, I can make the change.

> prompt is really optional, and is likely going to be something that you configure after having done a couple of iterations, playing with the model. We should make the user being able to get the playground env, as fast as possible, get him/her test, play, hack and understand what's going on.
> 
> I think this is not a great idea, especially for a first time user, to show a form with a lot of different options that they might not be familiar with (yet).
