### ISSUE TITLE
Deleting a model generates an error

### ISSUE THREAD

**Issue by jeffmaury** [projectatomic/ai-studio#649]
The error message:

![image](https://github.com/projectatomic/ai-studio/assets/695993/a5812a85-0b99-4253-8243-633d11c38238)

**Comment by vrothberg** [comment]
Should the entire directory of the model be deleted or only the model file itself?

**Comment by jeffmaury** [comment]
> Should the entire directory of the model be deleted or only the model file itself?

The whole directory as in the future a model can have several files

**Comment by axel7083** [comment]
Is this happening when the model is being mounted or in use ? If this is happening just after the download of a model ?

**Comment by jeffmaury** [comment]
> Is this happening when the model is being mounted or in use ? If this is happening just after the download of a model ?

Just after the download on my laptop
