### ISSUE TITLE
UX: make metadata for app stack a vertical column instead of card

### ISSUE THREAD

**Issue by mairin** [projectatomic/ai-studio#75]
Just a mockup tweak for the recipe screen layout

**Comment by mairin** [comment]
This was discussed in the UX call on Jan 25 as well.

Here's something I came up with @lstocchi - I don't know now that I've mocked it up that the show/hide function makes sense but tell me what you think.

I still need to mock up what is displayed once the application is running. I would like to have the details for the container / environment displayed where the progress info is. 

Anyway I would love to know what you think and if this makes sense or what else might work:

![image](https://github.com/projectatomic/ai-studio/assets/799683/6031fd6a-b8d7-4b35-8a99-fe13ccdb3a10)

![image](https://github.com/projectatomic/ai-studio/assets/799683/547456e0-e348-40ee-bb67-26865f74f340)

Here it is minimized (not sure on this one):
![image](https://github.com/projectatomic/ai-studio/assets/799683/fee869be-fab7-4882-8c66-777b1e890de1)

**Comment by lstocchi** [comment]
@mairin i love this ❤️ 
I also have doubts about the show/hide (maybe it's useful on smaller screen?) but it's really easy to implement so we can also decide later to remove/add it or show it based on screen size.
Regarding showing the details of container/env, Idk what you were thinking about ... i have access to the name of the containers, the ports opened, the pod name, their envs and volumes mounted. 
And maybe we can show a button to open the browser when the application is running

**Comment by lstocchi** [comment]
This is how it's evolving.
![image](https://github.com/projectatomic/ai-studio/assets/49404737/3f9e219e-805b-40b3-b63d-1d322ae3a7ae)

My questions:
1. where do we take the stars number? I guess it's the popularity property but it is something we set manually atm. Should we remove it until we decide how to set these numbers?
2. I don't have the application stack data. Is it something important that you want to have? If so, we need to update the config file of each sample app.

**Comment by mairin** [comment]
@lstocchi Good q's:

1. My initial thought when I started adding the stars was maybe this is some metadata we pull from huggingface. But I don't know if that makes sense. I don't think we want the overhead of building a rating system. I think maybe instead of making it a community rating, maybe we put a star on the model that is the "default" for the recipe? and no star if it isn't? Does that maek sense.

2. I think it would be really good to have the app stack data but I don't think it's critical. @slemeur what do you think? Is this a this sprint thing to resolve (adding application stack metadata to the sample app config files) or should we address post-Summit?

**Comment by mairin** [comment]
(That was fast and it is looking GREAT btw!!!)

**Comment by lstocchi** [comment]
> 1. My initial thought when I started adding the stars was maybe this is some metadata we pull from huggingface. But I don't know if that makes sense. I don't think we want the overhead of building a rating system. I think maybe instead of making it a community rating, maybe we put a star on the model that is the "default" for the recipe? and no star if it isn't? Does that maek sense.

Sounds good to me 👍

**Comment by mairin** [comment]
I'm gonna mark this as done because I think we have a solid initial design here. We can work out issues / iterations in PRs or feel free to reopen if need be.
