### ISSUE TITLE
Test the behaviour when the local-ai image is not present locally

### ISSUE THREAD

**Issue by feloy** [projectatomic/ai-studio#87]
For now, all the tests have been done with the local-ai image present locally. As the image is very big and very long to download, we have to see how we can handle the downloading of the image from the extension.

**Comment by lstocchi** [comment]
@MichaelClifford can help us here. This is an extract from slack.
```
I watched the demo and it was 34gb and seemed like the
model ran a bit slow. If you just want an image that can expose a rest API and use the llama.cpp backend, 
I think we could build that with a much smaller storage footprint
```

**Comment by MichaelClifford** [comment]
yeah, I'm working on creating a smaller image. I _almost_ have it ready. Still struggling with what appears to be a bug causing the the API server start time to be quite slow (like 2 minutes) in the container. But I can share what I have shortly.
